bash exp/energy_VAD/xvectors/xv_task_split10/0.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/1.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/2.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/3.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/4.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/5.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/6.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/7.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/8.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/9.sh &
bash exp/energy_VAD/xvectors/xv_task_split10/10.sh &
